import type { Metadata } from 'next';
import './globals.css';
import Providers from './Providers';
import localFont from 'next/font/local';

const NibProRegular = localFont({
	src: './fonts/NibPro-Regular.ttf',
	variable: '--font-nibpro-regular',
});

const NibProSemiBold = localFont({
	src: './fonts/NibPro-SemiBold.ttf',
	variable: '--font-nibpro-bold',
});

const NibProBold = localFont({
	src: './fonts/NibPro-Bold.ttf',
	variable: '--font-nibpro-bold',
});

export const metadata: Metadata = {
	title: 'tech novelty',
	description: 'Generated by create next app tech novelty',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${NibProRegular.variable} ${NibProSemiBold.variable} ${NibProBold.variable}`}
			>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
