import type { Metadata } from 'next';
import './globals.css';
import Providers from './Providers';
import localFont from 'next/font/local';

import {Poppins} from 'next/font/google';

const inter = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

const NibProRegular = localFont({
	src: './fonts/NibPro-Regular.ttf',
	variable: '--font-nibpro-regular',
});

const NibProSemiBold = localFont({
	src: './fonts/NibPro-SemiBold.ttf',
	variable: '--font-nibpro-bold',
});

const NibProBold = localFont({
	src: './fonts/NibPro-Bold.ttf',
	variable: '--font-nibpro-bold',
});

export const metadata: Metadata = {
	title: 'Mint App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' className={inter.className}>
			<body
				className={`${NibProRegular.variable} ${NibProSemiBold.variable} ${NibProBold.variable}`}
			>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
